### PR TITLE
port from ocamlbuild to dune

### PR DESCRIPTION
**Pull request by avsm**
This allows js_of_ocaml to be built as a standalone dune project with all its dependencies included more easily.

### CODE REVIEW

**Comment by Drup** [comment]
Looks good!

@hhugo If you have no opposition, I'll merge by the end of the day.

**Comment by hhugo** [comment]
This only thing that is not preserved is the gh-pages target in the Makefile

**Comment by hhugo** [comment]
That said, I'm not opposed.

**Comment by Drup** [comment]
@hhugo There is no ocsigen documentary machinery for this repo ?

**Comment by avsm** [comment]
@hhugo I updated the RELEASE.md with `dune-release` instructions. WIth that, it automatically uploads a tagged version of the docs and a tarball to GH and pushes to gh-pages and submits an opam-repository PR.

**Comment by avsm** [comment]
Gentle ping; can this be released?

**Comment by avsm** [comment]
@hhugo @Drup - the newer dune releases in opam might help with this now.

**Comment by avsm** [comment]
@Drup can I get a release of this into opam please?

**Pull request merged**
