### PR TITLE
Deploy odoc to GitHub Pages from GitHub Actions

### PR DESCRIPTION
**Pull request by smorimoto**
Set the "source" to GitHub Actions from here: https://github.com/ocsigen/reactiveData/settings/pages

Ref: https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta

### CODE REVIEW

**Comment by smorimoto** [comment]
@balat Could you take care of this? It seems that the administrator permission is required to change it.

**Comment by balat** [comment]
Done. How to test this?

**Comment by smorimoto** [comment]
You can check it from here:

- http://ocsigen.github.io/reactiveData
- https://github.com/ocsigen/reactiveData/actions/runs/12464446963

**Comment by smorimoto** [comment]
I think the link in the repository description needs to be updated!

**Pull request merged**
